language: android

android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.1

notifications:
  email: false

sudo: required

after_success:
  - bash <(curl -s https://codecov.io/bash)